services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../chat-app-client:/workspace:cached
    command: sleep infinity
    depends_on:
      - server
    ports:
      - 3000:3000

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../chat-app-server:/workspace:cached
    command: sleep infinity
    ports:
      - 3001:3001